title: "Glorified Studios Staff"
lang: "en-GB"
repository: GlorifiedStudios/Team

collections:
  teams:
    order:
      - board.md
      - development.md
      - moderation.md
  staff:
    order:
      - internet.md
    output: true

plugins:
  - kramdown
  - kramdown-parser-gfm
  - liquid
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-avatar
  - jekyll-remote-theme
  - jemoji
  - jekyll-mentions
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-titles-from-headings
